{ inputs, nixpkgs }:
let
  inherit (import ./lib.nix { inherit inputs nixpkgs; }) baseConfig mkTest;
in
{
  # bootstrap.just: exercises git-init -> add-machine -> secrets-init ->
  # deploy-local end-to-end through the real `ft` CLI wrapper, against a
  # scratch consumer repo at /tmp/repo. `ssh` and `nixos-anywhere` are
  # replaced with stubs (generate-facts needs a real remote target;
  # nixos-anywhere needs real disk hardware) — every other step (git, nix
  # eval, ssh-keygen, ssh-to-age, the justfile control flow itself) is real.
  vm-bootstrap-workflow = mkTest {
    name = "ft-bootstrap-workflow";
    nodes.machine =
      { pkgs, ... }:
      {
        imports = [ baseConfig ];
        ft.repoPath = "/tmp/repo";
        ft.cli.enable = true;
        environment.systemPackages = [
          pkgs.ssh-to-age
          (pkgs.symlinkJoin {
            name = "fake-bootstrap-deps";
            paths = [
              # Stands in for the real target generate-facts would scan over ssh.
              (pkgs.writeShellScriptBin "ssh" ''
                printf '%s' '{"system":{"system":"x86_64-linux"}}'
              '')
              # Records its argv instead of actually wiping a disk.
              (pkgs.writeShellScriptBin "nixos-anywhere" ''
                printf '%s\n' "$@" > /tmp/nixos-anywhere-args.log
              '')
              # Real ssh-keygen — secrets-init needs the genuine implementation.
              (pkgs.runCommand "ssh-keygen-only" { } ''
                mkdir -p $out/bin
                ln -s ${pkgs.openssh}/bin/ssh-keygen $out/bin/ssh-keygen
              '')
            ];
          })
        ];
      };
    testScript = ''
      machine.wait_for_unit("multi-user.target")

      # Pre-seed git-init's answers so it never blocks on an interactive prompt.
      machine.succeed("mkdir -p /tmp/repo/var/git")
      machine.succeed("printf 'Test User' > /tmp/repo/var/git/user-name")
      machine.succeed("printf 'test@example.com' > /tmp/repo/var/git/user-email")
      machine.succeed("printf 'git@example.com:test/test-repo' > /tmp/repo/var/git/remote")

      # git-init: repoPath must record the @src convention, not the transient
      # bootstrap $PWD.
      machine.succeed("ft git-init")
      machine.succeed("test -d /tmp/repo/.git")
      machine.succeed("grep -qx '/src/repo' /tmp/repo/var/local/repoPath")

      # add-machine (fresh): scaffolds the machine and generates hardware facts.
      machine.succeed("ft add-machine alpha 127.0.0.1 alice")
      machine.succeed("test -f /tmp/repo/machines/alpha/default.nix")
      machine.succeed("test -s /tmp/repo/machines/alpha/var/facter.json")
      machine.succeed("grep -qx alpha /tmp/repo/var/local/machineName")

      # add-machine (retry): facter.json must be regenerated even though the
      # machine directory already exists from the previous run.
      machine.succeed("rm /tmp/repo/machines/alpha/var/facter.json")
      machine.succeed("ft add-machine alpha 127.0.0.1 alice")
      machine.succeed("test -s /tmp/repo/machines/alpha/var/facter.json")

      # add-machine (prebuilt): a hand-written machine directory must still get
      # its var/local state recorded and its facts generated, and must not be
      # clobbered by the scaffold template.
      machine.succeed("mkdir -p /tmp/repo/machines/beta")
      machine.succeed("printf '{ }: { }' > /tmp/repo/machines/beta/default.nix")
      machine.succeed("ft add-machine beta 127.0.0.1 bob")
      machine.succeed("grep -qx beta /tmp/repo/var/local/machineName")
      machine.succeed("test -s /tmp/repo/machines/beta/var/facter.json")
      machine.succeed("grep -qx '{ }: { }' /tmp/repo/machines/beta/default.nix")

      # secrets-init: writes the sops key configuration for the machine.
      machine.succeed("ft secrets-init alpha")
      machine.succeed("grep -q '&alpha' /tmp/repo/var/secrets/.sops.yaml")

      # deploy-local: stages the full consumer repo onto the target's @src
      # path and bundles the SSH host key generated by secrets-init.
      machine.succeed("ft deploy-local alpha")
      machine.succeed("test -f /tmp/bootstrap-alpha/src/repo/machines/alpha/default.nix")
      machine.succeed("test -f /tmp/bootstrap-alpha/src/repo/var/local/repoPath")
      machine.succeed("test -f /tmp/bootstrap-alpha/etc/ssh/ssh_host_ed25519_key")
      machine.succeed("grep -qx -- '--extra-files' /tmp/nixos-anywhere-args.log")
      machine.succeed("grep -qx root@localhost /tmp/nixos-anywhere-args.log")
    '';
  };
}
